### PR TITLE
Add Jokes Service and Controller

### LINKED ISSUE #7: Add Joke Controller and Tests
# Acceptance Criteria:

- [ ] There is <tt>JokeController.java</tt> file in the `src/main/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] <tt>JokeController.java</tt> implements a class that implements an API endpoint that takes in the necessary
      parameters, calls the <tt>JokeQueryService</tt>, and returns the results.
- [ ] The file  <tt>JokeController.java</tt> file make appropriate use of the
      annotations `@Tag`, `@Operation` and `@Parameter` to document the API.
- [ ] The controller endpoint shows up on the Swagger UI page.
- [ ] There is a <tt>JokeControllerTests.java</tt> file in the `src/test/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] The tests in <tt>JokeControllerTests</tt> provide 100% coverage of <tt>JokeController</tt> for both jacoco and pitest.

# Details

See the assignment description at https://ucsb-cs156.github.io/w24/lab/team01 for details.

### PR DESCRIPTION
**Pull request by Ze-el**
In this PR, we add an endpoint `/api/jokes/get` that can be used to get jokes for a given category and amount and a test for this controller.

Dev Deployment Links:
http://team01-ze-el-dev.dokku-13.cs.ucsb.edu
http://team01-ze-el-dev.dokku-13.cs.ucsb.edu/swagger-ui/index.html

Closes #7

### CODE REVIEW

**Comment by Daoyijiucsb** [comment]
The link doesn't work for me. 
Did you sync and rebuild a dokku? The code seems correct.

**Comment by Ze-el** [comment]
There was a mistake while posting the link I have edited it now. You should be able to view them now.

**Comment by Daoyijiucsb** [comment]
LGTM!
The link works fine now.

**Review by liamlizard — APPROVED** [review]
LGTM!
Code looks good and runs as expected on dokku.

**Review by owenjpark — APPROVED** [review]
LGTM, API works as expected on Swagger dokku dev deployment

**Comment by gretchenlam** [comment]
LGTM! Dev deployment and tests look great

**Pull request merged**
