### PR TITLE
Add Location Controller and Tests

### LINKED ISSUE #9: Add Location Controller and Tests
# Acceptance Criteria:

- [ ] There is <tt>LocationController.java</tt> file in the `src/main/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] <tt>LocationController.java</tt> implements a class that implements an API endpoint that takes in the necessary
      parameters, calls the <tt>LocationQueryService</tt>, and returns the results.
- [ ] The file  <tt>LocationController.java</tt> file make appropriate use of the
      annotations `@Tag`, `@Operation` and `@Parameter` to document the API.
- [ ] The controller endpoint shows up on the Swagger UI page.
- [ ] There is a <tt>LocationControllerTests.java</tt> file in the `src/test/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] The tests in <tt>LocationControllerTests</tt> provide 100% coverage of <tt>LocationController</tt> for both jacoco and pitest.

# Details

See the assignment description at https://ucsb-cs156.github.io/w24/lab/team01 for details.

### PR DESCRIPTION
**Pull request by liamlizard**
In this PR, we add an endpoint 'api/locations/get' that can be used to get a list of locations that match a given location name.

Dev Deployment Links:
http://team01-liamlizard-dev.dokku-13.cs.ucsb.edu/
http://team01-liamlizard-dev.dokku-13.cs.ucsb.edu/swagger-ui/index.html#/Location%20info%20from%20nominatim.org/getLocation

Closes #9

### CODE REVIEW

**Comment by Daoyijiucsb** [comment]
LGTM
It is working on both local and dokku server

**Comment by gretchenlam** [comment]
LGTM! dev deployment server and tests look good

**Comment by Ze-el** [comment]
LGTM.
Swagger and dokku deployment look good

**Review by owenjpark — APPROVED** [review]
LGTM, Swagger UI has the Location API that works properly

**Review by Ze-el — APPROVED** [review]
LGTM.
Swagger and dokku deployment look good

**Pull request merged**
